language: ruby
rvm:
  - 2.6.3
cache: bundler
#install: 
#  - bundle install
#  - gem install s3_website
#  - gem install jekyll
script: bundle exec jekyll build
after_success: s3_website push
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: "jden-me"
  local_dir: _site
  endpoint: https://sos-ch-dk-2.exo.io
  acl: public_read
  on:
    branch: poole
