language: ruby
rvm:
  - 2.6.3
cache: bundler
before_install:
  - sudo apt-get -y install libgsl-dev
script: bundle exec jekyll build --incremental
before_deploy: pip install --user awscli
deploy:
  provider: script
  skip_cleanup: true
#  script: ~/.local/bin/aws s3 sync --endpoint-url https://sos-ch-dk-2.exo.io --acl public-read --delete --size-only _site s3://jden-me --region=ch-dk-2
  script: ~/.local/bin/aws s3 sync --endpoint-url https://s3.fr-par.scw.cloud --acl public-read --delete --size-only _site s3://jden-me --region=fr-par
  on:
    branch: poole
after_deploy: 
  - ./bunnyCDN.sh $BUNNYCDN $ZONE_ID