language: ruby
rvm:
  - 2.6.3
cache: bundler
script: bundle exec jekyll build
#deploy:
#  provider: s3
#  skip_cleanup: true
#  access_key_id: $S3_ACCESS_KEY_ID
#  secret_access_key: $S3_SECRET_KEY
#  bucket: "jden-me"
#  local_dir: _site
#  endpoint: https://sos-ch-dk-2.exo.io
#  acl: public_read
#  on:
#    branch: poole
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: 1234968f138843be9bb7c16be48833f6
  secret_access_key: d23051404f1f42be98277d58e39e5350
  bucket: "jden-me"
  local_dir: _site
  endpoint: https://object.api.ams.fuga.cloud
  acl: public_read
  on:
    branch: poole
#deploy:
#  provider: s3
#  skip_cleanup: true
#  access_key_id: mErfvZXNtGfd
#  secret_access_key: qm4W7v38n2VvykjntcbyAtXaWNBaXPp5
#  bucket: "jden-me"
#  local_dir: _site
#  endpoint: https://object.api.ams.fuga.cloud
#  acl: public_read
#  on:
#    branch: poole